package: a11y_docs
version: '1.0.0'
author: Your Name
supportpage: github.com/yourusername/a11y_docs

page:
    title: 'Barrierefreiheit'
    icon: rex-icon fa-universal-access
    block: system
    subpages:
        cheatsheet:
            title: 'Cheatsheet'
        screenreader:
            title: 'Emulator'
            hasLayout: false
            linkAttr: { target: _blank }

requires:
    redaxo: '^5.18.0'
    php:
        version: '>=8.1'
